services:

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    volumes:
      - grafana-config:/etc/grafana
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    build:
      context: ./prometheus
      args:
        - PROMETHEUS_VERSION=${PROMETHEUS_VERSION}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - logporter

  logporter:
    image: lifailon/logporter:${LOGPORTER_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_LOG_METRICS=false
      - DOCKER_LOG_CUSTOM_METRICS=false
      - DOCKER_LOG_CUSTOM_QUERY=\"(err|error|ERR|ERROR)\"

volumes:
  grafana-config:
  grafana-storage:
  prometheus_data:
